phase 1 changes - typos, destroyxerath, and alphabetical lists
webstersw/CitySaver pull request #2
Opened 2020-11-30 22:51 UTC by WKWCoding

I don't know how to test this before I push it. But I think it should work.

2020-11-30 23:07 UTC, webstersw requested changes

2020-11-30 23:07 UTC, webstersw commented on src/index.ts
> +				message.channel.send(`I can't do that. Try 'save' or 'destroy', followed by a city name.`);
change this to "try !citysave help"

2020-11-30 23:07 UTC, webstersw commented on src/commandHelpers.ts
> +    const destroyed = getCityList(false).sort((n1,n2) => n1 - n2);;
Wrong method, add this to getAlphabeticalList

2020-11-30 23:07 UTC, webstersw commented on src/index.ts
> +            case "alist":
nit: tabbing

2020-12-08 01:54 UTC, webstersw requested changes

2020-12-08 01:54 UTC, webstersw commented on src/index.ts
> +const tok = "Nzg1NjY1OTg0NTUwOTI4Mzg0.X87Kdw.gb3G-4AtTNiAixQdIyIhemuS3kQ";
token revealed - rekt - use an environment variable

2020-12-08 02:16 UTC, WKWCoding commented on src/index.ts
> +const tok = "Nzg1NjY1OTg0NTUwOTI4Mzg0.X87Kdw.gb3G-4AtTNiAixQdIyIhemuS3kQ";
check your messages

2020-12-08 05:25 UTC, webstersw commented on src/commandHelpers.ts
> +    var destroyed = JSON.parse(JSON.stringify(getCityArray(false)));
JSON.parse(JSON.stringify(... no

2020-12-08 05:27 UTC, webstersw commented on src/commandHelpers.ts
> +    var destroyed = JSON.parse(JSON.stringify(getCityArray(false)));
try one of these
```
// "Spread"
{ ...food }
// "Object.assign"
Object.assign({}, food)
```

2020-12-08 23:18 UTC, webstersw approved these changes

2020-12-09 23:46 UTC, merged